services:
  api:
    container_name: bookhaven-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=bookhaven_db;Username=postgres;Password=1234
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres

  postgres:
    container_name: bookhaven-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookhaven_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080" 
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  postgres-data: